// This is an autogenerated file and should not be edited.

// Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Package version contains constants to indicate the current version of
// ECS Local Container Endpoints. It is autogenerated
package version

// Please DO NOT commit any changes to this file unless you know what
// you are doing.

// Version is the version of ECS Local Container Endpoints
const Version = "1.0.1"

// AgentVersionCompatibility is the Latest Agent Version that ECS Local Container Endpoints is compatible with
const AgentVersionCompatibility = "1.27.0"

// GitDirty indicates the cleanliness of the git repo when it was built
const GitDirty = true

// GitShortHash is the short hash of this build
const GitShortHash = "e5f7969"
