pull_request_rules:
  - name: Merge for developers
    conditions:
      - base~=(mainline|rename-commands)
      - "#approved-reviews-by>=2"
      - approved-reviews-by=@aws/aws-ecs-devx
      - -approved-reviews-by~=author
      - -label~=(WIP|do-not-merge)
      - -title~=(WIP|wip)
      - -merged
      - -closed
      - author!=dependabot[bot]
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}
  - name: Merge for bots
    conditions:
      - base=mainline
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - author=dependabot[bot]
      - -title~=(WIP|wip)
      - -label~=(WIP|do-not-merge)
      - -merged
      - -closed
    actions:
      review:
        type: APPROVE
      queue:
        name: default
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}

